//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mine2CraftWinApp.CompleteItemService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompleteItemService.ICompleteItemService")]
    public interface ICompleteItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/GetCompleteItems", ReplyAction="http://tempuri.org/ICompleteItemService/GetCompleteItemsResponse")]
        Mine2CraftWebApp.CompleteItem.CompleteItemDto[] GetCompleteItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/GetCompleteItems", ReplyAction="http://tempuri.org/ICompleteItemService/GetCompleteItemsResponse")]
        System.Threading.Tasks.Task<Mine2CraftWebApp.CompleteItem.CompleteItemDto[]> GetCompleteItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/CreateCompleteItem", ReplyAction="http://tempuri.org/ICompleteItemService/CreateCompleteItemResponse")]
        Mine2CraftWebApp.CompleteItem.CompleteItemDto[] CreateCompleteItem(string name, int durability, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/CreateCompleteItem", ReplyAction="http://tempuri.org/ICompleteItemService/CreateCompleteItemResponse")]
        System.Threading.Tasks.Task<Mine2CraftWebApp.CompleteItem.CompleteItemDto[]> CreateCompleteItemAsync(string name, int durability, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/DeleteCompleteItem", ReplyAction="http://tempuri.org/ICompleteItemService/DeleteCompleteItemResponse")]
        Mine2CraftWebApp.CompleteItem.CompleteItemDto[] DeleteCompleteItem(Mine2CraftWebApp.CompleteItem.CompleteItemDto completeItemDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/DeleteCompleteItem", ReplyAction="http://tempuri.org/ICompleteItemService/DeleteCompleteItemResponse")]
        System.Threading.Tasks.Task<Mine2CraftWebApp.CompleteItem.CompleteItemDto[]> DeleteCompleteItemAsync(Mine2CraftWebApp.CompleteItem.CompleteItemDto completeItemDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompleteItemServiceChannel : Mine2CraftWinApp.CompleteItemService.ICompleteItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompleteItemServiceClient : System.ServiceModel.ClientBase<Mine2CraftWinApp.CompleteItemService.ICompleteItemService>, Mine2CraftWinApp.CompleteItemService.ICompleteItemService {
        
        public CompleteItemServiceClient() {
        }
        
        public CompleteItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompleteItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompleteItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompleteItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mine2CraftWebApp.CompleteItem.CompleteItemDto[] GetCompleteItems() {
            return base.Channel.GetCompleteItems();
        }
        
        public System.Threading.Tasks.Task<Mine2CraftWebApp.CompleteItem.CompleteItemDto[]> GetCompleteItemsAsync() {
            return base.Channel.GetCompleteItemsAsync();
        }
        
        public Mine2CraftWebApp.CompleteItem.CompleteItemDto[] CreateCompleteItem(string name, int durability, string description) {
            return base.Channel.CreateCompleteItem(name, durability, description);
        }
        
        public System.Threading.Tasks.Task<Mine2CraftWebApp.CompleteItem.CompleteItemDto[]> CreateCompleteItemAsync(string name, int durability, string description) {
            return base.Channel.CreateCompleteItemAsync(name, durability, description);
        }
        
        public Mine2CraftWebApp.CompleteItem.CompleteItemDto[] DeleteCompleteItem(Mine2CraftWebApp.CompleteItem.CompleteItemDto completeItemDto) {
            return base.Channel.DeleteCompleteItem(completeItemDto);
        }
        
        public System.Threading.Tasks.Task<Mine2CraftWebApp.CompleteItem.CompleteItemDto[]> DeleteCompleteItemAsync(Mine2CraftWebApp.CompleteItem.CompleteItemDto completeItemDto) {
            return base.Channel.DeleteCompleteItemAsync(completeItemDto);
        }
    }
}
