//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompleteItemService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompleteItemDto", Namespace="http://schemas.datacontract.org/2004/07/Mine2CraftWebApp.CompleteItem")]
    public partial class CompleteItemDto : object
    {
        
        private string DescriptionField;
        
        private int DurabilityField;
        
        private System.Guid IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Durability
        {
            get
            {
                return this.DurabilityField;
            }
            set
            {
                this.DurabilityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompleteItemService.ICompleteItemService")]
    public interface ICompleteItemService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/GetCompleteItems", ReplyAction="http://tempuri.org/ICompleteItemService/GetCompleteItemsResponse")]
        CompleteItemService.CompleteItemDto[] GetCompleteItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/GetCompleteItems", ReplyAction="http://tempuri.org/ICompleteItemService/GetCompleteItemsResponse")]
        System.Threading.Tasks.Task<CompleteItemService.CompleteItemDto[]> GetCompleteItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/CreateCompleteItem", ReplyAction="http://tempuri.org/ICompleteItemService/CreateCompleteItemResponse")]
        CompleteItemService.CompleteItemDto[] CreateCompleteItem(string name, int durability, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/CreateCompleteItem", ReplyAction="http://tempuri.org/ICompleteItemService/CreateCompleteItemResponse")]
        System.Threading.Tasks.Task<CompleteItemService.CompleteItemDto[]> CreateCompleteItemAsync(string name, int durability, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/DeleteCompleteItem", ReplyAction="http://tempuri.org/ICompleteItemService/DeleteCompleteItemResponse")]
        CompleteItemService.CompleteItemDto[] DeleteCompleteItem(CompleteItemService.CompleteItemDto completeItemDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompleteItemService/DeleteCompleteItem", ReplyAction="http://tempuri.org/ICompleteItemService/DeleteCompleteItemResponse")]
        System.Threading.Tasks.Task<CompleteItemService.CompleteItemDto[]> DeleteCompleteItemAsync(CompleteItemService.CompleteItemDto completeItemDto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICompleteItemServiceChannel : CompleteItemService.ICompleteItemService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CompleteItemServiceClient : System.ServiceModel.ClientBase<CompleteItemService.ICompleteItemService>, CompleteItemService.ICompleteItemService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CompleteItemServiceClient() : 
                base(CompleteItemServiceClient.GetDefaultBinding(), CompleteItemServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICompleteItemService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompleteItemServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CompleteItemServiceClient.GetBindingForEndpoint(endpointConfiguration), CompleteItemServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompleteItemServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CompleteItemServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompleteItemServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CompleteItemServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompleteItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public CompleteItemService.CompleteItemDto[] GetCompleteItems()
        {
            return base.Channel.GetCompleteItems();
        }
        
        public System.Threading.Tasks.Task<CompleteItemService.CompleteItemDto[]> GetCompleteItemsAsync()
        {
            return base.Channel.GetCompleteItemsAsync();
        }
        
        public CompleteItemService.CompleteItemDto[] CreateCompleteItem(string name, int durability, string description)
        {
            return base.Channel.CreateCompleteItem(name, durability, description);
        }
        
        public System.Threading.Tasks.Task<CompleteItemService.CompleteItemDto[]> CreateCompleteItemAsync(string name, int durability, string description)
        {
            return base.Channel.CreateCompleteItemAsync(name, durability, description);
        }
        
        public CompleteItemService.CompleteItemDto[] DeleteCompleteItem(CompleteItemService.CompleteItemDto completeItemDto)
        {
            return base.Channel.DeleteCompleteItem(completeItemDto);
        }
        
        public System.Threading.Tasks.Task<CompleteItemService.CompleteItemDto[]> DeleteCompleteItemAsync(CompleteItemService.CompleteItemDto completeItemDto)
        {
            return base.Channel.DeleteCompleteItemAsync(completeItemDto);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICompleteItemService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICompleteItemService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57660/CompleteItemService/CompleteItemService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CompleteItemServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICompleteItemService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CompleteItemServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICompleteItemService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICompleteItemService,
        }
    }
}
